/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package HEMS;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Fatimah
 */
public class PatientEnquiry extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    public PatientEnquiry() throws SQLException {
        initComponents();
        conn = DBUtil.getConnection();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pqueryPanel = new javax.swing.JPanel();
        searchField = new javax.swing.JTextField();
        fnameButton = new javax.swing.JButton();
        lnameButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        queryList = new javax.swing.JList();
        pdetailsPanel = new javax.swing.JPanel();
        mrnLabel = new javax.swing.JLabel();
        addLabel = new javax.swing.JLabel();
        sexLabel = new javax.swing.JLabel();
        telLabel = new javax.swing.JLabel();
        occLabel = new javax.swing.JLabel();
        nokLabel = new javax.swing.JLabel();
        mrnField = new javax.swing.JTextField();
        addField = new javax.swing.JTextField();
        sexField = new javax.swing.JTextField();
        telField = new javax.swing.JTextField();
        occField = new javax.swing.JTextField();
        nokField = new javax.swing.JTextField();
        getButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pqueryPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Find Patient", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        fnameButton.setText("First Name");
        fnameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameButtonActionPerformed(evt);
            }
        });

        lnameButton.setText("Last name");
        lnameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(queryList);

        pdetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Patient Details"));

        mrnLabel.setText("MRN: ");

        addLabel.setText("Address: ");

        sexLabel.setText("Sex: ");

        telLabel.setText("Phone No: ");

        occLabel.setText("Occupation: ");

        nokLabel.setText("Next of Kin: ");

        mrnField.setEditable(false);
        mrnField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mrnFieldKeyTyped(evt);
            }
        });

        addField.setEditable(false);

        sexField.setEditable(false);

        telField.setEditable(false);

        occField.setEditable(false);

        nokField.setEditable(false);

        javax.swing.GroupLayout pdetailsPanelLayout = new javax.swing.GroupLayout(pdetailsPanel);
        pdetailsPanel.setLayout(pdetailsPanelLayout);
        pdetailsPanelLayout.setHorizontalGroup(
            pdetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pdetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pdetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addLabel)
                    .addComponent(telLabel)
                    .addComponent(occLabel)
                    .addComponent(nokLabel)
                    .addComponent(sexLabel)
                    .addComponent(mrnLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pdetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addField)
                    .addComponent(nokField)
                    .addGroup(pdetailsPanelLayout.createSequentialGroup()
                        .addGroup(pdetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sexField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mrnField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(occField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 210, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );

        pdetailsPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {mrnField, occField, sexField, telField});

        pdetailsPanelLayout.setVerticalGroup(
            pdetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pdetailsPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pdetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mrnLabel)
                    .addComponent(mrnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pdetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pdetailsPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(addLabel))
                    .addGroup(pdetailsPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(addField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pdetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sexLabel)
                    .addComponent(sexField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(pdetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telLabel)
                    .addComponent(telField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pdetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(occLabel)
                    .addComponent(occField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pdetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nokLabel)
                    .addComponent(nokField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        getButton.setText("GET");
        getButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pqueryPanelLayout = new javax.swing.GroupLayout(pqueryPanel);
        pqueryPanel.setLayout(pqueryPanelLayout);
        pqueryPanelLayout.setHorizontalGroup(
            pqueryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pqueryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pqueryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pqueryPanelLayout.createSequentialGroup()
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fnameButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lnameButton))
                    .addComponent(getButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(42, 42, 42)
                .addComponent(pdetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pqueryPanelLayout.setVerticalGroup(
            pqueryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pqueryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pdetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(pqueryPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pqueryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fnameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(getButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pqueryPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {fnameButton, lnameButton, searchField});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pqueryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pqueryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fnameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameButtonActionPerformed
        // TODO add your handling code here:
        DefaultListModel dlm = new DefaultListModel();
        String pquery = "SELECT * FROM patientregister WHERE firstname = ?";
        try {
            pst = conn.prepareStatement(pquery);
            pst.setString(1, searchField.getText());
            rs = pst.executeQuery();
            while(rs.next()){
                String fname = rs.getString("firstname");
                String lname = rs.getString("surname");
                
                dlm.addElement(fname+" "+lname);
               
            }
             queryList.setModel(dlm);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_fnameButtonActionPerformed

    private void lnameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameButtonActionPerformed
        // TODO add your handling code here:
        DefaultListModel dlm = new DefaultListModel();
        String pquery = "SELECT * FROM patientregister WHERE surname = ?";
        try {
            pst = conn.prepareStatement(pquery);
            pst.setString(1, searchField.getText());
            rs = pst.executeQuery();
            
            while(rs.next()){
                String fname = rs.getString("firstname");
                String lname = rs.getString("surname");
                String fullname = fname+ " "+ lname;
                dlm.addElement(fullname);               
            }
            queryList.setModel(dlm);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_lnameButtonActionPerformed

    private void getButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getButtonActionPerformed
        // TODO add your handling code here:
        if(queryList.isSelectionEmpty()){
                JOptionPane.showMessageDialog(null, "Please select patient.");  
        }
        else{
          try {

               String fullname = (String)queryList.getSelectedValue();
               int space = fullname.indexOf(" ");
               String fname = fullname.substring(0, space);
               String lname = fullname.substring(space+1, fullname.length());

               String sql = "select * from patientregister where firstname = ? and surname = ?";
               pst = conn.prepareStatement(sql);
               pst.setString(1, fname);
               pst.setString(2, lname);
               rs = pst.executeQuery();

                   if(rs.next()){
                       String mrn = rs.getString("mrn");
                       mrnField.setText(mrn);
                       String sex = rs.getString("sex");
                       sexField.setText(sex);
                       String add = rs.getString("address");
                       addField.setText(add);
                       String tel = rs.getString("telephone");
                       telField.setText(tel);
                       String occ = rs.getString("occupation");
                       occField.setText(occ);
                       String nok = rs.getString("nextofkin");
                       nokField.setText(nok);

                   }


               } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e);
               }
        }
    }//GEN-LAST:event_getButtonActionPerformed

    private void mrnFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mrnFieldKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c))|| (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_mrnFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientEnquiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientEnquiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientEnquiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientEnquiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new PatientEnquiry().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(PatientEnquiry.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addField;
    private javax.swing.JLabel addLabel;
    private javax.swing.JButton fnameButton;
    private javax.swing.JButton getButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lnameButton;
    private javax.swing.JTextField mrnField;
    private javax.swing.JLabel mrnLabel;
    private javax.swing.JTextField nokField;
    private javax.swing.JLabel nokLabel;
    private javax.swing.JTextField occField;
    private javax.swing.JLabel occLabel;
    private javax.swing.JPanel pdetailsPanel;
    private javax.swing.JPanel pqueryPanel;
    private javax.swing.JList queryList;
    private javax.swing.JTextField searchField;
    private javax.swing.JTextField sexField;
    private javax.swing.JLabel sexLabel;
    private javax.swing.JTextField telField;
    private javax.swing.JLabel telLabel;
    // End of variables declaration//GEN-END:variables
}
